[project]
name = "text2sql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.121.2",
    "flake8>=7.3.0",
    "graphviz>=0.21",
    "langchain>=1.0.5",
    "langchain-community>=0.4.1",
    "langchain-core>=1.0.4",
    "langchain-openai>=1.0.2",
    "langgraph-sdk>=0.2.9",
    "langgraph[server]>=1.0.3",
    "langserve>=0.3.3",
    "mysql-connector-python>=9.5.0",
    "python-dotenv>=1.2.1",
    "sqlalchemy>=2.0.44",
    "sse-starlette>=3.0.3",
    "uvicorn>=0.38.0",
]
